site_name: Management from the Trenches
site_url: https://bmhash.github.io

theme:
    name: material
    palette:
        primary: indigo
        accent: deep orange
     font:
        text:
        code: Roboto Mono

extra_css:
    - css/extra.css
