site_name: Management from the Trenches
site_url: https://bmhash.github.io
site_description: A repo with lessons learned on managing projects

theme:
    name: material
    palette:
      primary: indigo
      accent: deep orange
    font:
      text: Ubuntu Mono
